apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::520072122793:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-1wEbVaKLbmYz
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: | #
      - groups:
      - roboshop-junior
      userarn: arn:aws:iam::520072122793:user/sunil
      username: sunil
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-23T14:14:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1152"
  uid: da2790dc-f407-4970-9f03-c7521396f7e9